# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-03-11 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='peopleinfo',
            table='PeopleInfo',
        ),
    ]
